---
- name: Copy ssh public key
  ansible.builtin.fetch:
    src: "{{ ssh_key_path }}"
    dest: /tmp/
    flat: yes
  delegate_to: "{{ source_server }}"

- name: Create .ssh for target user
  ansible.builtin.file:
    path: /home/{{ target_user }}/.ssh
    state: directory
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: '0700'

- name: Copy public key to  authorized_keys
  authorized_key:
    user: "{{ target_user }}"
    state: present
    key: "{{ lookup('file', '/tmp/' + ssh_key_path | basename) }}"